app/mediation/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField
from wtforms.validators import DataRequired

class MediationForm(FlaskForm):
    """Form to start new mediation"""
    title = StringField('Title', validators=[DataRequired()])
    invitee = StringField('Username or Email', validators=[DataRequired()])
    submit = SubmitField('Start Mediation')

app/mediation/__init__.py
from flask import Blueprint

mediation_bp = Blueprint("mediation", __name__)

from . import routes

app/mediation/routes.py
from flask import render_template, redirect, url_for, flash, request, jsonify, session
from flask_login import current_user, login_required
from flask_socketio import join_room, send, emit
from app import socketio
from app.mediation import mediation_bp
from app import db
from app.models import User, Mediation, Agreement
from app.mediation.forms import MediationForm
from app.mediation.mediation_services import PrivateMediation, PublicMediation, MessagePublic

PUBLIC_MEDIATION_MODEL = "gpt-4"
open_mediators_private = {}
open_mediators_public = {}


def get_current_statement_from_db(mediation_id, user_id):
    mediation = Mediation.query.get_or_404(mediation_id)
    if user_id == mediation.initiator_id:
        return mediation.initiator_conflict_statement
    return mediation.other_conflict_statement


@mediation_bp.route('/start_mediation', methods=['GET', 'POST'])
@login_required
def start_mediation():
    global open_mediators_private
    form = MediationForm()
    if form.validate_on_submit():
        # Check if invitee is a username or email
        user = User.query.filter_by(username=form.invitee.data).first() or User.query.filter_by(
            email=form.invitee.data).first()

        other_user_id = user.id if user else None

        # Create new mediation
        mediation = Mediation(title=form.title.data, initiator_id=current_user.id, other_id=other_user_id)
        db.session.add(mediation)
        db.session.commit()

        if user:
            flash('Mediation started successfully!')
        else:
            # Send an email (mockup function)
            send_invite_email(form.invitee.data)
            flash('Invitation sent to email!')

        # create Mediation instance
        mediator = PrivateMediation(mediation_id=mediation.mediation_id, user_id=current_user.id)

        if mediation.mediation_id not in open_mediators_private.keys():
            open_mediators_private[mediation.mediation_id] = {}
        open_mediators_private[mediation.mediation_id][current_user.id] = mediator
        # session["mediation"][mediation.mediation_id] = {} # register mediation in the session
        return redirect(url_for('mediation.private_mediation', mediation_id=mediation.mediation_id))

    return render_template('mediation/start_mediation.html', form=form)


@mediation_bp.route('/continue_mediation')
@login_required
def continue_mediation():
    # Retrieve mediations for the logged-in user
    mediations = Mediation.query.filter(
        (Mediation.initiator_id == current_user.id) | (Mediation.other_id == current_user.id)).all()
    return render_template('mediation/continue_mediation.html', mediations=mediations)


@mediation_bp.route('/mediation_detail/<int:mediation_id>')
@login_required
def mediation_detail(mediation_id):
    global open_mediators_private
    global open_mediators_public
    mediation = Mediation.query.get_or_404(mediation_id)

    # Check if the user is part of this mediation
    if current_user.id not in [mediation.initiator_id, mediation.other_id]:
        flash('You are not part of this mediation.')
        return redirect(url_for('main.index'))

    # Check if conflict statements exist
    if current_user.id == mediation.initiator_id:
        if mediation.initiator_statement_committed:
            if mediation_id not in open_mediators_public.keys():
                mediator = PublicMediation(
                    mediation_id,
                    model=PUBLIC_MEDIATION_MODEL
                )
                open_mediators_public[mediation_id] = mediator
            return redirect(url_for('mediation.public_mediation', mediation_id=mediation_id))
        else:
            if mediation_id not in open_mediators_private.keys():
                open_mediators_private[mediation_id] = {}

            if current_user.id not in open_mediators_private[mediation_id].keys():
                mediator = PrivateMediation(
                    mediation_id=mediation_id,
                    user_id=current_user.id,
                    load_from_db=True
                )
                open_mediators_private[mediation.mediation_id][current_user.id] = mediator

            return redirect(url_for('mediation.private_mediation', mediation_id=mediation_id))
    else:
        if mediation.other_statement_committed:
            if mediation_id not in open_mediators_public.keys():
                mediator = PublicMediation(
                    mediation_id,
                    model=PUBLIC_MEDIATION_MODEL,
                )
                open_mediators_public[mediation_id] = mediator
            return redirect(url_for('mediation.public_mediation', mediation_id=mediation_id))
        else:
            if mediation_id not in open_mediators_private.keys():
                open_mediators_private[mediation_id] = {}

            if current_user.id not in open_mediators_private[mediation_id].keys():
                mediator = PrivateMediation(
                    mediation_id=mediation_id,
                    user_id=current_user.id,
                    load_from_db=True
                )

                open_mediators_private[mediation.mediation_id][current_user.id] = mediator
            return redirect(url_for('mediation.private_mediation', mediation_id=mediation_id))


@mediation_bp.route('/private_mediation/<int:mediation_id>')
def private_mediation(mediation_id):
    global open_mediators_private
    if mediation_id not in open_mediators_private.keys():
        open_mediators_private[mediation_id] = {}
    if current_user.id not in open_mediators_private[mediation_id].keys():
        new_mediator = PrivateMediation(mediation_id)
        open_mediators_private[mediation_id][current_user.id] = new_mediator
    mediator = open_mediators_private[mediation_id][current_user.id]
    messages = mediator.mediator.chat_history[1:]  # load chat history
    statement = get_current_statement_from_db(user_id=current_user.id, mediation_id=mediation_id)

    return render_template(
        'mediation/private_mediation.html',
        mediation_id=mediation_id,
        messages=messages,
        current_statement=statement,
    )

@mediation_bp.route('/handle_request_private', methods=['POST'])
def handle_request_private():
    """route to interact with the private mediator"""
    data = request.get_json()
    mediation_id = int(data.get('mediation_id'))
    mediator = open_mediators_private[mediation_id][current_user.id]
    mediation = Mediation.query.get_or_404(mediation_id)
    if mediation.initiator_id == current_user.id:
        mediator.current_conflict_statement = mediation.initiator_conflict_statement
    else:
        mediator.current_conflict_statement = mediation.other_conflict_statement

    input_data = data.get('input')

    # the user can edit the conflict statement in a text window. If he types in something there it is
    # returned by the statementInput field in the json.
    conflict_statement = data.get('statementInput')
    if conflict_statement == "None" or conflict_statement == "":
        conflict_statement = None

    if conflict_statement is not None and conflict_statement != mediator.current_conflict_statement:
        mediator.current_conflict_statement = conflict_statement
        if mediation.initiator_id == current_user.id:
            mediation.initiator_conflict_statement = conflict_statement
        else:
            mediation.other_conflict_statement = mediator.current_conflict_statement
        input_data = f"I adjusted the conflict statement: {conflict_statement}. {input_data}"
        # TODO: also make a system message.
        db.session.commit()

    output_data = mediator.send_request_to_openai(input_data)
    show_button = "###show_button###" in output_data

    mediator.add_to_db({"role": "user", "content": input_data})

    statement_text = mediator.extract_initial_statement()

    if statement_text:
        bot_message = mediator.mediator.chat_history[-2]["content"]
        mediator.add_to_db({"role": "assistant", "content": bot_message})
        mediator.current_conflict_statement = statement_text
        if mediation.initiator_id == current_user.id:
            mediation.initiator_conflict_statement = mediator.current_conflict_statement

        else:
            mediation.other_conflict_statement = mediator.current_conflict_statement
        mediator.add_to_db(mediator.mediator.chat_history[-1])
    else:
        bot_message = output_data
        mediator.add_to_db({"role": "assistant", "content": bot_message})
    db.session.commit()

    return jsonify({'output': bot_message, 'statementText': statement_text, 'showButton': show_button})

@mediation_bp.route('/submit_statement', methods=['POST'])
@login_required
def submit_statement():
    """Submit the comitting statement"""
    data = request.get_json()
    mediation_id = int(data.get('mediation_id'))
    statement = data.get('statement')
    mediation = Mediation.query.get_or_404(mediation_id)
    if mediation.initiator_id == current_user.id:
        mediation.initiator_statement_committed = True
        mediation.initiator_conflict_statement = statement
    else:
        mediation.other_statement_committed = True
        mediation.other_conflict_statement = statement

    db.session.commit()
    # TODO: redirect or some other logic for ending
    if mediation.initiator_statement_committed and mediation.other_statement_committed:
        socketio.emit('all_statements_submitted', {'status': 'complete'}, room=str(mediation_id))
    url = (url_for('mediation.public_mediation', mediation_id=mediation.mediation_id))
    return jsonify({"redirect": url})

@socketio.on('join')
def on_join(data):
    """join chatroom"""
    room = data['mediation_id']
    join_room(room)
    send({"message": f"a user has entered the room."}, room=room)


@mediation_bp.route('/public_mediation/<int:mediation_id>')
def public_mediation(mediation_id: int):
    """route to load up the public mediation page and all its functionality"""

app/templates/mediation/continue_mediation.html
<h2>Continue Mediation</h2>
<ul>
    {% for mediation in mediations %}
        <li>
            <a href="{{ url_for('mediation.mediation_detail', mediation_id=mediation.mediation_id) }}">
                Mediation: {{ mediation.title }}
            </a>
        </li>
    {% endfor %}
</ul>

app/templates/mediation/private_mediation.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Private Mediation</title>
 <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/private_mediation.css') }}">
  <script src="{{ url_for('static', filename='js/private_mediation.js') }}" defer></script>
</head>
<body data-mediation-id="{{ mediation_id }}">
  <div class="container">
    <div class="chat-area">
      <div id="chatDisplay">
        <!-- Chat messages will be added here -->
              <!-- Loop through messages and display them  if there is a chat history-->
        {% for message in messages %}
            {% if message.role != 'system' %}
                <div class="{{ 'user-message' if message.role == 'user' else 'bot-message' }}">
                    {{ message.content }}
                </div>
            {% endif %}
        {% endfor %}
        <div id="typing-indicator" class="bot-message" style="display: none;">
          <span class="dot"></span>
          <span class="dot"></span>
          <span class="dot"></span>
        </div>
      </div>
      <div class="input-area">
        <textarea id="chatInput" placeholder="Type your message here..." rows="1"></textarea>
        <button id="submitChat">Submit</button>
      </div>
    </div>
    <div class="statement-area">
      <button id="showStatement">Show Statement Area</button>
      <textarea id="statementInput" {% if not current_statement %}class="hidden"{% endif %}>{{ current_statement }}</textarea>
      <button id="submitStatement">Submit Statement</button>
    </div>
  </div>
</body>
</html>

app/templates/mediation/public_mediation.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Public Mediation</title>
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='styles/public_mediation.css') }}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
</head>

<body data-mediation-id="{{ mediation_id }}">

    <script>
        const user_id = "{{ user_id }}";
    </script>
    <button id="toggleSidebar" class="toggle-sidebar">
        <i class="fas fa-bars"></i> <!-- Font Awesome icon for a menu -->
    </button>

        <div class="sidebar" id="sidebar">

            <!-- Main navigation buttons -->
            <button id="viewAgreementsBtn">View Agreements</button>

            <!-- Agreement List Container -->
            <div id="agreementList" class="hidden">
                <h3>Agreements</h3>
                <ul id="agreementTitles">
                    {% for agreement in agreements %}
                    <li>
                        <!-- The title is clickable and contains a data attribute to store the agreement ID -->
                        <h3 class="agreement-title" data-agreement-id="{{ agreement.id }}">
                            {{ agreement.title }}
                        </h3>
                        <!-- The content of the agreement is hidden initially and also contains the agreement ID data attribute -->
                        <p class="agreement-content hidden" data-agreement-id="{{ agreement.id }}">
                            {{ agreement.text }}
                        </p>
                    </li>
                    {% endfor %}
                </ul>
            </div>

            <!-- Selected Agreement Display Container -->
            <div id="selectedAgreement" class="hidden">
                <h3 id="selectedAgreementTitle"></h3>
                <p id="selectedAgreementContent"></p>
            </div>
        </div>

    <div class="container">
        <div class="statement-area" id="userStatementArea">
            <h2>Your Statement
                <button id="toggleStatementBtn" class="toggle-btn">Toggle</button>
                <button id="generateListBtn" class="hidden">Generate List</button>
            </h2>
            <textarea id="userStatement" readonly>{{ conflict_statement_user }}</textarea>
        </div>
        <div class="chat-area">
            <div id="chatDisplay">

                <!-- Loop through messages and display them if there is a chat history-->
                {% for id, role, content in messages %}
                    {% if role == 'assistant' %}
                        {% set css_class = 'bot-message' %}
                    {% elif id == user_id %}
                        {% set css_class = 'user-message' %}
                    {% else %}
                        {% set css_class = 'other-user-message' %}
                    {% endif %}
                    <div class="{{ css_class }}">
                        {{ content }}
                    </div>
                {% endfor %}
            </div>

            <div class="input-area">
                <textarea id="chatInput" placeholder="Type a message..."></textarea>
                <button id="submitChat" disabled>Submit</button>
            </div>
        </div>
        <div class="statement-area" id="otherStatementArea">
            <h2>Statement {{ name_other }}</h2>
            <textarea id="otherStatement" readonly>{{ conflict_statement_other }}</textarea>
        </div>
    </div>
    <div id="modal-overlay">
        <div>
            <h2>Agreement</h2>
            <p id="agreement-text"></p>
            <h3>Your Comments</h3>
            <textarea id="user-comments"></textarea>
            <button id="agree-btn">Agree</button>
            <button id="disagree-btn">Disagree</button>
        </div>
    </div>
    <script src="{{ url_for('static', filename='js/public_mediation.js') }}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/socket.io/4.0.1/socket.io.js"></script>

</body>
</html>

app/templates/mediation/start_mediation.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Start Mediation</title>
    <!-- You can include any CSS libraries or styles here if needed -->
</head>
<body>

<h2>Start Mediation</h2>

<form action="{{ url_for('mediation.start_mediation') }}" method="post">
    {{ form.hidden_tag() }}
    <p>
        {{ form.title.label }}<br>
        {{ form.title(size=32) }}
    </p>
    <p>
        {{ form.invitee.label }}<br>
        {{ form.invitee(size=32) }}
    </p>
    <p>{{ form.submit() }}</p>
</form>

<!-- You can include any JS libraries or scripts here if needed -->

</body>
</html>